# Generated by Django 4.2.1 on 2023-05-26 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Truck",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("unique_number", models.CharField(max_length=5, unique=True, verbose_name="Truck number")),
                ("payload_capacity", models.PositiveIntegerField(verbose_name="Max cargo weight carried by the truck")),
                (
                    "current_location",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="locations.location"),
                ),
            ],
        ),
    ]
