version: '3'
services:
  db:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_DB=welbex
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
       - "5430:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis
    ports:
       - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=vhost
    ports:
      - "15671:15672"
      - "5671:5672"

#  flower:
#    platform: linux/amd64
#    image: mher/flower
#    environment:
#      - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@127.0.0.1:5671/vhost
#      - FLOWER_PORT=8888
#    ports:
#     - 8888:8888
