# Generated by Django 4.2.1 on 2023-05-29 12:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cargo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(limit_value=1000)],
                        verbose_name="Weight of the cargo",
                    ),
                ),
                ("description", models.TextField(max_length=200, verbose_name="Cargo description")),
                (
                    "delivery_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_cargos",
                        to="locations.location",
                        verbose_name="Cargo delivery location",
                    ),
                ),
                (
                    "pick_up_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pick_up_cargos",
                        to="locations.location",
                        verbose_name="Cargo pick-up location",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
